### ISSUE TITLE
Not able to see any queries only TPS is shown

### ISSUE THREAD

**Issue by subhajeet2107** [dalibo/pg_activity#102]
No running queries or anything is being shown all i can see is this:

I ran sudo -u postgres pg_activity -U postgres

Am i missing anyting my postgresql is version 11 with citus extension

![screen shot 2019-01-06 at 2 18 12 pm](https://user-images.githubusercontent.com/9478415/50734018-eb8eb480-11bd-11e9-8dc6-d6e2575cd820.png)

**Comment by gbour** [comment]
I have the same issue with debian testing version (`1.4.0-1`) onto a postgresql 10.6 running in docker (`docker:10` image from docker hub)

**Comment by julmon** [comment]
What's going on when you run a long query like `select pg_sleep(20);` ? Do you see it ?

Please see this comment https://github.com/julmon/pg_activity/issues/86#issuecomment-446631152

**Comment by vpArth** [comment]
You may be forgot to select database for monitoring: `-d my_project_db`.
`postgres` database is under monitoring on your screenshot.

**Comment by cadenassog** [comment]
Same problem, using teh -d parameter. I did'n see anything

**Comment by blogh** [comment]
Hi,

pg_activity uses different queries to get : 

- settings from pg_settings
- version info using  version()
- queries and number of connections from pg_stat_activity
- locks from pg_locks
- tps from pg_database using pg_stat_get_db_xact_commit() and pg_stat_get_db_xact_rollback()
- and more ( eg : pg_cancel_backend() and pg_terminate_backend() )

Thoses queries dont show in the query tab because all queries from pg_activities backend are considered as noise and are ignored. On the other hand, the transactions used to get the info for pg_activity's reporting are still accounted for by postgres in pg_stat_get_db_xact_commit() and pg_stat_get_db_xact_commit(). Therefore it's possible (and frequent) to have a non zero TPS and no queries in the tab.

Do you have queries running ? (an application running or pgbench)
If not / your re not sure : did you try [this](https://github.com/dalibo/pg_activity/issues/102#issuecomment-469027567) ?

Benoit

**Comment by blogh** [comment]
A [FAQ](https://github.com/dalibo/pg_activity#faq) has been added to the README.md to document possible reasons why queries might not show.

If you have more question on this topic feel free to reopen the issue.
