### ISSUE TITLE
ImportError: No module named psycopg2

### ISSUE THREAD

**Issue by ArturFormella** [dalibo/pg_activity#170]
Hello! I have the following problem

```
$sudo apt install pg-activity
Reading package lists... Done
Building dependency tree
Reading state information... Done
pg-activity is already the newest version (1.5.0-1.pgdg20.04+1).
0 upgraded, 0 newly installed, 0 to remove and 31 not upgraded.

$pg_activity
Traceback (most recent call last):
  File "/usr/local/bin/pg_activity", line 4, in <module>
    __import__('pkg_resources').run_script('pg-activity==1.5.0', 'pg_activity')
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1469, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/pg_activity-1.5.0-py2.7.egg/EGG-INFO/scripts/pg_activity", line 42, in <module>

ImportError: No module named psycopg2
```
but it works this way:
```
$python3 -m pip install pg_activity psycopg2-binary
/home/user/.local/bin/pg_activity
```
How to repair version from apt?

Other info:
```
Ubuntu 20.04.1 LTS
PostgreSQL 13.1

$/home/aformella/.local/bin/pg_activity --version
pg_activity 2.0.3

```

**Comment by dlax** [comment]
> $pg_activity
> Traceback (most recent call last):
>   File "/usr/local/bin/pg_activity", line 4, in <module>
>     __import__('pkg_resources').run_script('pg-activity==1.5.0', 'pg_activity')
>  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 666, in run_script

I suspect that pg_activity got previously installed through `sudo pip install` or such (as evidenced by `/usr/local/` prefix).
The Debian/Ubuntu package would install into `/usr/bin/pg_activity` and `/usr/lib/python3/dist-packages`.

> How to repair version from apt?

I suggest to uninstall the version in `/usr/local` either with `sudo pip uninstall pg_activity` (if you have a python2 version of `pip` installed system-wide) or by cleaning files in that prefix by hand (at least `/usr/local/bin/pg_activity`).

(I'm closing the issue since it's not a problem in `pg_activity` itself.)
