### ISSUE TITLE
Unecessary aliases in import

### ISSUE THREAD

**Issue by yoyonel** [dalibo/pg_activity#418]
https://github.com/dalibo/pg_activity/blob/2feac0e6900280986245e6c172c30b7912567e38/pgactivity/pg.py#L20-L27

Maybe i miss something but it seems not useful to import and make an alias with the same name:
```python
from psycopg.errors import [ERROR_NAME] as [ERROR_NAME]
```

**Comment by dlax** [comment]
These are indeed not needed at runtime but this is needed in order to let Mypy (and probably other type checkers) know that these names are explicitly re-exported during type checking. This is the [implicit_reexport=false](https://mypy.readthedocs.io/en/stable/config_file.html#confval-implicit_reexport) behaviour of Mypy, which is triggered by `--strict` more that we use.

**Comment by yoyonel** [comment]
Thanks for your answer :-)
